apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: r58mtak6m-go
  janus-idp.io/tekton: r58mtak6m-go
  backstage.io/kubernetes-id: r58mtak6m-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: r58mtak6m-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
